version: "2.2"

services:

  mentoria-build:
    build: .
    image: ulissesmb/mentoria:${TAG}
    networks:
      - mentoria-network

  mentoria-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mentoria-mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
    env_file:
      - ./.env
    networks:
      - mentoria-network

  mentoria-web:
    image: ulissesmb/mentoria:${TAG}
    depends_on:
        - mentoria-build
        - mentoria-db
    container_name: mentoria-php
    working_dir: /var/www/html
    volumes:
        - ${LOCAL_PATH}:/var/www/html
    ports:
        - 8080:80
    networks:
        - mentoria-network
    links:
        - mentoria-db
networks:
    mentoria-network:
        driver: bridge