version: "3.8"
services:

    # PHP service
    buildphp:
        image: ulissesmb-mentoria-php:0.1
        build: .
        #container_name: ulissesmb-mentoria-php:0.1
        working_dir: /var/www/html
        networks:
            - app-network

    webphp:
        image: ulissesmb-mentoria-php:0.1
        depends_on:
            - buildphp
        container_name: mentoria-php-v1
        working_dir: /var/www/html
        volumes:
            - /c/developer/php/www:/var/www/html
        ports:
            - 8080:80
        networks:
            - app-network
networks:
    app-network:
        driver: bridge